Pending stuff.

diff --git a/frontend/gcompile b/frontend/gcompile
--- a/frontend/gcompile
+++ b/frontend/gcompile
@@ -1,4 +1,9 @@
-#!/bin/sh
+#! /bin/bash
+
+if [ $# -ne 2 ]; then
+	echo "Usage: $0 <gramola_src_prog> <java_target_class_name>"
+	exit 65
+fi
 
 SOURCE=$1
 JTARGET=$2
@@ -6,6 +11,15 @@ TARGET_DIR=../src/
 BIN_DIR=../bin/
 CLASSPATH=../lib/*:.
 
+if [ ! -d ../bin ]; then
+	mkdir ../bin
+fi
+
+if [ ! -e ../lib/gramola.jar ]; then
+	echo "ERROR: Could not find gramola.jar."
+	exit 1
+fi
+	
 python codegen.py $SOURCE $JTARGET
 mv *.java $TARGET_DIR
 javac -cp $CLASSPATH ${TARGET_DIR}*.java
diff --git a/frontend/gexe b/frontend/gexe
--- a/frontend/gexe
+++ b/frontend/gexe
@@ -1,8 +1,18 @@
-#/usr/sh
+#! /bin/bash
+
+if [ $# -ne 1 ]; then
+	echo "Usage: $0 <java_class_name>"
+	exit 65
+fi
 
 TARGET=$1
 CLASSPATH=../lib/*:.
 
+if [ ! -e ../bin/$TARGET ]; then
+	echo "ERROR: Could not find ../bin/$TARGET.class"
+	exit 1
+fi
+
 cd ../bin
 
-java -cp $CLASSPATH $1
+java -cp $CLASSPATH $TARGET
